name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y build-essential libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Install Raylib
      run: |
        sudo apt-get install -y cmake
        git clone https://github.com/raysan5/raylib.git
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install

    - name: Build with Makefile
      run: make
